package org.warnier.zhang.notes.mybatis3.generator.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.warnier.zhang.notes.mybatis3.generator.model.Link;
import org.warnier.zhang.notes.mybatis3.generator.model.LinkExample;

public interface LinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_LINK
     *
     * @mbg.generated Thu Aug 01 09:37:45 CST 2019
     */
    long countByExample(LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_LINK
     *
     * @mbg.generated Thu Aug 01 09:37:45 CST 2019
     */
    int deleteByExample(LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_LINK
     *
     * @mbg.generated Thu Aug 01 09:37:45 CST 2019
     */
    int deleteByPrimaryKey(Long linkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_LINK
     *
     * @mbg.generated Thu Aug 01 09:37:45 CST 2019
     */
    int insert(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_LINK
     *
     * @mbg.generated Thu Aug 01 09:37:45 CST 2019
     */
    int insertSelective(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_LINK
     *
     * @mbg.generated Thu Aug 01 09:37:45 CST 2019
     */
    List<Link> selectByExampleWithRowbounds(LinkExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_LINK
     *
     * @mbg.generated Thu Aug 01 09:37:45 CST 2019
     */
    List<Link> selectByExample(LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_LINK
     *
     * @mbg.generated Thu Aug 01 09:37:45 CST 2019
     */
    Link selectByPrimaryKey(Long linkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_LINK
     *
     * @mbg.generated Thu Aug 01 09:37:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") Link record, @Param("example") LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_LINK
     *
     * @mbg.generated Thu Aug 01 09:37:45 CST 2019
     */
    int updateByExample(@Param("record") Link record, @Param("example") LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_LINK
     *
     * @mbg.generated Thu Aug 01 09:37:45 CST 2019
     */
    int updateByPrimaryKeySelective(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_LINK
     *
     * @mbg.generated Thu Aug 01 09:37:45 CST 2019
     */
    int updateByPrimaryKey(Link record);
}